### ISSUE TITLE
[bug]: Main server down 

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#215]
@ryanfortner Our main server is inaccessible now. I checked the logs and found this started two hours ago. I tried connecting to the VPS via ssh, but it failed. I tried booting and restarting, both failed.

I have reported this incident to Fosshost.

**Comment by ryanfortner** [comment]
@hmsjy2017 this issue has been resolved, thanks to the folks on the Fosshost discord server.

**Comment by hmsjy2017** [comment]
@ryanfortner Do you know why this problem occurred?

**Comment by ryanfortner** [comment]
![image](https://user-images.githubusercontent.com/71036629/152147205-169d0ba0-cb1b-4c60-9b62-036556d4161c.jpeg)

It seems to be an issue on Fosshost's end, nothing we can do to prevent it from happening in the future.

**Comment by hmsjy2017** [comment]
I think this issue can be closed now.

**Comment by ryanfortner** [comment]
![image](https://user-images.githubusercontent.com/71036629/152335991-9d747a90-fb8a-46c5-b9b7-5a148b2dd8cc.jpeg)

Main mirror is down again, looks like fosshost will be sending an email shortly.

**Comment by ryanfortner** [comment]
@hmsjy2017 have you received any emails from fosshost?

**Comment by hmsjy2017** [comment]
@ryanfortner No. I think that we can switch to another server once the primary server is back to normal.

**Comment by ryanfortner** [comment]
here are some updates.

- We will need to migrate to a new vm. Fosshost's `bos4` region had a hardware issue and they are no longer going to be using it. I have already created a new vm, it is called `main-node`.
- Thankfully, Hampton Moore was able to help me get the needed data off of the affected vm. I have transferred all that data over to the `main-node` vm. I also updated the dns record of apt.raspbian-addons.org to point to the new vm.

however @hmsjy2017 I am having problems with caddy giving a 403 error, I am not sure what may be causing it because the `/root/raspbian-addons` folder is already owned by www-data... do you mind taking a look please? after the 403 error is fixed we can go ahead and finally close this issue :)
